package scanner;


/**
 * 
 * @author Sam Giese
 * Sets all of the token types
 *
 */
public enum TokenType{
	WRITE, READ, LBRACKET, RBRACKET, ID, ILLEGAL, SLASH, BECOMES, ASTERISK,
	LPARENTHESES, RPARENTHESES, LESSTHAN, GREATERTHAN, LESSTHANOREQUAL, GREATERTHANOREQUAL,
	PROGRAM, REAL, COLON, THEN, PROCEDURE, PERIOD, COMMA, SEMICOLON, WHILE, VAR, AND,
	BEGIN, DIV, DO, OR, MOD, INTEGER, NOT, IF, ELSE, FUNCTION, END, ARRAY, NOTEQUAL, OF,
	MINUS, PLUS, EQUAL, RETURN, RELOP, FLOAT
}

